#POST
POST 'http://localhost:3000/library'

###
GET http://localHost:3000/book/all

###
POST http://localHost:3000/book/save
Content-Type: application/json

{
    "nameBook": "Harry Potter don varitas",
    "amountBook": 2,
    "genBook": "Potterorrifico",
    "sumBook": "La historia de potter y su varita",
    "yearbook": 1889,
    "authbook": "yo",
    "postbook":"https://cdn.culturagenial.com/es/imagenes/harry-potter-libros-1-cke.jpg"
}

