#POST
POST http://localhost:3000/library
Content-Type: application/json

{
    "docUser":1095299063,
    "nameUser":"Andrey",
    "emailUser":"andreyvr07@gmail.com",
    "passUser":"12345",
    "phoneUser":3219567693,
    "addressUser":"Piedecuesta-Santander"
}

###
GET http://localHost:3000/book/all

###
POST http://localHost:3000/book/save
Content-Type: application/json

{
    "nameBook": "pruebita",
    "amountBook": 10,
    "genBook": "comedio?",
    "sumBook": "si mi chamos",
    "yearbook": 2024,
    "authbook": "que es auth",
    "postbook":"www.rear"
}

